create table public.rooms (
  id integer generated by default as identity primary key,
  name text not null,
  name_eng text not null unique,
  area integer not null check (area > 0),
  capacity integer not null check (capacity > 0),
  min integer not null check (min > 0 and min <= capacity),
  is_liked boolean not null default false,
  images text[] not null default '{}',
  description text not null,
  description_eng text not null
);

create table public.seasons (
  id integer generated by default as identity primary key,
  name text not null unique,
  ranges jsonb not null
);

create table public.holidays (
  id integer generated by default as identity primary key,
  holiday_name text not null,
  holiday_date date not null unique
);

create table public.prices (
  id integer generated by default as identity primary key,
  room_id integer not null
    references public.rooms(id)
    on update cascade
    on delete restrict,
  season_id integer not null
    references public.seasons(id)
    on update cascade
    on delete restrict,
  weekday_price integer not null check (weekday_price >= 0),
  weekend_price integer not null check (weekend_price >= 0),
  holiday_price integer not null check (holiday_price >= 0),
  unique (room_id, season_id)
);

create table public.reservations (
  id integer generated by default as identity primary key,
  room_id integer not null
    references public.rooms(id)
    on update cascade
    on delete restrict,
  check_in_date date not null,
  check_out_date date not null,
  total_price integer not null check (total_price >= 0),
  number_of_guests integer not null check (number_of_guests > 0),
  customer_name text not null,
  phone_number text not null,
  created_at timestamptz not null default now(),
  check (check_out_date > check_in_date)
);

create index reservations_room_date_idx
  on public.reservations (
    room_id,
    check_in_date,
    check_out_date
  );

alter table public.rooms enable row level security;
alter table public.seasons enable row level security;
alter table public.holidays enable row level security;
alter table public.prices enable row level security;
alter table public.reservations enable row level security;
